version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: trunk
  schedule:
    interval: "cron"
    cronjob: "9 12 * 2,5,8,11 4#1"
  pull-request-branch-name:
    separator: "-"
  groups:
    actions-version:
      applies-to: version-updates
      patterns:
      - '*'
    actions-security:
      applies-to: security-updates
      patterns:
      - '*'
