#!/usr/bin/env python3
"""
Dipole Moment FDR Fork-and-Clone Workflow Manager

This script orchestrates the fork-and-clone methodology for measuring dipole moment
fluctuation-dissipation relation (FDR). It:

1. Runs two simulations: one with +E₀ and one with -E₀ perturbation
2. Combines the dipole moment data from both clones
3. Computes the linear response χ_μ(t) = (μ⃗^(+)(t) - μ⃗^(-)(t)) / (2E₀)
4. Validates the FDR by comparing autocorrelation-predicted susceptibility with measured response

Usage:
    python dipole_fdr_workflow.py [base_simulation_args] --dipole-fdr-field-strength 1e-5

The script will automatically:
- Run plus clone with --dipole-response-sign +1
- Run minus clone with --dipole-response-sign -1  
- Analyze both results and validate FDR

Author: AI Assistant
Created: 2025-09-26 (Phase 4)
"""

import sys
import os
import argparse
import subprocess
import time
import numpy as np
import pandas as pd
from pathlib import Path
from typing import List, Dict, Tuple, Optional
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def run_simulation(args: List[str], clone_type: str, replica: int = 0) -> bool:
    """
    Run a single simulation (plus or minus clone).
    
    Args:
        args: Base simulation arguments 
        clone_type: Either 'plus' or 'minus'
        replica: Replica number
        
    Returns:
        True if simulation completed successfully
    """
    sign = "+1" if clone_type == "plus" else "-1"
    clone_args = args + [
        "--enable-dipole-fdr",
        "--enable-dipole-response", 
        f"--dipole-response-sign", sign,
        f"--replica", str(replica)
    ]
    
    logger.info(f" Starting {clone_type} clone (sign={sign}) for replica {replica}")
    logger.info(f"Command: python 18_unified_cavity_dynamics.py {' '.join(clone_args)}")
    
    start_time = time.time()
    try:
        result = subprocess.run(
            ["python", "18_unified_cavity_dynamics.py"] + clone_args,
            check=True,
            capture_output=True,
            text=True
        )
        
        elapsed = time.time() - start_time
        logger.info(f" {clone_type.capitalize()} clone completed successfully in {elapsed:.1f}s")
        logger.info(f"   STDOUT: {len(result.stdout.splitlines())} lines")
        if result.stderr:
            logger.warning(f"   STDERR: {result.stderr[:200]}...")
            
        return True
        
    except subprocess.CalledProcessError as e:
        elapsed = time.time() - start_time
        logger.error(f" {clone_type.capitalize()} clone failed after {elapsed:.1f}s")
        logger.error(f"   Exit code: {e.returncode}")
        logger.error(f"   STDOUT: {e.stdout[:500]}...")
        logger.error(f"   STDERR: {e.stderr[:500]}...")
        return False

def find_output_files(replica: int = 0) -> Dict[str, Optional[Path]]:
    """
    Find output files generated by the simulations.
    
    Args:
        replica: Replica number
        
    Returns:
        Dictionary with file paths for dipole FDR data
    """
    files = {
        'dipole_fdr': f"dipole_fdr_replica_{replica}.csv",
        'autocorr_plus': f"dipole_fdr_replica_{replica}_autocorrelation.csv", 
        'autocorr_minus': f"dipole_fdr_replica_{replica}_autocorrelation.csv",
        'response_plus': None,  # These might have different names
        'response_minus': None
    }
    
    found_files = {}
    for key, filename in files.items():
        if filename and Path(filename).exists():
            found_files[key] = Path(filename)
            logger.info(f" Found {key}: {filename}")
        else:
            found_files[key] = None
            if filename:
                logger.warning(f" Missing {key}: {filename}")
    
    return found_files

def analyze_fdr_data(plus_file: Path, minus_file: Path, autocorr_file: Path, 
                     field_strength: float, field_direction: List[float]) -> Dict:
    """
    Analyze the fork-and-clone FDR data.
    
    Args:
        plus_file: CSV file with dipole moments from plus clone
        minus_file: CSV file with dipole moments from minus clone  
        autocorr_file: CSV file with autocorrelation data
        field_strength: Applied electric field strength E₀
        field_direction: Electric field direction vector (normalized)
        
    Returns:
        Dictionary with FDR analysis results
    """
    logger.info(" Analyzing fork-and-clone FDR data...")
    
    try:
        # Load dipole moment data
        plus_data = pd.read_csv(plus_file)
        minus_data = pd.read_csv(minus_file)
        autocorr_data = pd.read_csv(autocorr_file)
        
        logger.info(f"   Plus clone data: {len(plus_data)} timesteps")
        logger.info(f"   Minus clone data: {len(minus_data)} timesteps") 
        logger.info(f"   Autocorrelation data: {len(autocorr_data)} timesteps")
        
        # Normalize field direction
        field_dir = np.array(field_direction)
        field_dir = field_dir / np.linalg.norm(field_dir)
        
        # Extract relevant columns
        time = plus_data['time_ps'].values
        
        # Dipole moments projected onto field direction
        mu_plus = (plus_data['dipole_x'].values * field_dir[0] + 
                   plus_data['dipole_y'].values * field_dir[1] + 
                   plus_data['dipole_z'].values * field_dir[2])
        
        mu_minus = (minus_data['dipole_x'].values * field_dir[0] + 
                    minus_data['dipole_y'].values * field_dir[1] + 
                    minus_data['dipole_z'].values * field_dir[2])
        
        # Calculate linear response χ_μ(t) = (μ^(+)(t) - μ^(-)(t)) / (2E₀)
        response_susceptibility = (mu_plus - mu_minus) / (2.0 * field_strength)
        
        # Get autocorrelation-predicted susceptibility  
        autocorr_time = autocorr_data['time_ps'].values
        autocorr_values = autocorr_data['autocorrelation'].values
        
        # Static susceptibility from response (long-time average)
        static_response = np.mean(response_susceptibility[-100:])  # Last 100 points
        
        # Static susceptibility from autocorrelation (integral)
        # χ₀ = ∫₀^∞ C_μ(t) dt / (k_B T)
        kT_au = 3.1668e-6 * 100.0  # Assuming 100K temperature in a.u.
        dt = autocorr_time[1] - autocorr_time[0] if len(autocorr_time) > 1 else 0.1
        static_autocorr = np.trapz(autocorr_values, dx=dt) / kT_au
        
        # Calculate correlation coefficient between time-dependent susceptibilities
        # (need to interpolate to common time grid)
        min_time = max(time[0], autocorr_time[0])
        max_time = min(time[-1], autocorr_time[-1])
        common_time = np.linspace(min_time, max_time, 1000)
        
        response_interp = np.interp(common_time, time, response_susceptibility)
        autocorr_interp = np.interp(common_time, autocorr_time, autocorr_values / kT_au)
        
        correlation_coef = np.corrcoef(response_interp, autocorr_interp)[0, 1]
        
        results = {
            'time': time,
            'response_susceptibility': response_susceptibility,
            'autocorr_time': autocorr_time,
            'autocorr_susceptibility': autocorr_values / kT_au,
            'static_response': static_response,
            'static_autocorr': static_autocorr,
            'fdr_ratio': static_response / static_autocorr if static_autocorr != 0 else float('inf'),
            'correlation_coefficient': correlation_coef,
            'field_strength': field_strength,
            'field_direction': field_dir,
            'temperature_K': 100.0,  # Assumed
            'kT_au': kT_au
        }
        
        logger.info(f" FDR Analysis Results:")
        logger.info(f"   Static χ (response): {static_response:.6e}")
        logger.info(f"   Static χ (autocorr): {static_autocorr:.6e}")
        logger.info(f"   FDR ratio: {results['fdr_ratio']:.3f} (should be ≈ 1.0)")
        logger.info(f"   Time correlation: {correlation_coef:.3f} (should be > 0.8)")
        
        return results
        
    except Exception as e:
        logger.error(f" FDR analysis failed: {e}")
        return {}

def save_fdr_results(results: Dict, output_file: str = "fdr_analysis.csv"):
    """Save FDR analysis results to CSV file."""
    if not results:
        logger.warning(" No results to save")
        return
        
    try:
        # Save time-dependent data
        time_data = pd.DataFrame({
            'time_ps': results['time'],
            'response_susceptibility': results['response_susceptibility']
        })
        
        autocorr_extended = pd.DataFrame({
            'time_ps': results['autocorr_time'], 
            'autocorr_susceptibility': results['autocorr_susceptibility']
        })
        
        # Merge on time grid
        combined = pd.merge(time_data, autocorr_extended, on='time_ps', how='outer').sort_values('time_ps')
        combined.to_csv(output_file, index=False)
        
        # Save summary statistics
        summary_file = output_file.replace('.csv', '_summary.txt')
        with open(summary_file, 'w') as f:
            f.write("Dipole Moment FDR Analysis Summary\n")
            f.write("==================================\n\n")
            f.write(f"Electric field strength: {results['field_strength']:.2e}\n")
            f.write(f"Electric field direction: {results['field_direction']}\n")
            f.write(f"Temperature: {results['temperature_K']:.1f} K\n")
            f.write(f"kT (a.u.): {results['kT_au']:.6e}\n\n")
            f.write(f"Static susceptibility (response): {results['static_response']:.6e}\n")
            f.write(f"Static susceptibility (autocorr): {results['static_autocorr']:.6e}\n")
            f.write(f"FDR ratio (response/autocorr): {results['fdr_ratio']:.3f}\n")
            f.write(f"Time correlation coefficient: {results['correlation_coefficient']:.3f}\n\n")
            f.write("FDR Validation:\n")
            if abs(results['fdr_ratio'] - 1.0) < 0.2:
                f.write(" PASS: FDR ratio within 20% of theoretical value\n")
            else:
                f.write(" FAIL: FDR ratio deviates significantly from theory\n")
            if results['correlation_coefficient'] > 0.8:
                f.write(" PASS: Strong correlation between response and autocorr\n")
            else:
                f.write(" FAIL: Weak correlation between response and autocorr\n")
        
        logger.info(f" FDR results saved to {output_file} and {summary_file}")
        
    except Exception as e:
        logger.error(f" Failed to save FDR results: {e}")

def main():
    """Main fork-and-clone FDR workflow."""
    parser = argparse.ArgumentParser(
        description="Dipole Moment FDR Fork-and-Clone Workflow",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic FDR measurement with exponential coupling
  python dipole_fdr_workflow.py --coupling-type exponential --exponential-amplitude 1e-3 \\
                                --exponential-decay-time 1.0 --runtime 100 \\
                                --dipole-fdr-field-strength 1e-5
  
  # FDR with specific field direction and higher precision  
  python dipole_fdr_workflow.py --coupling-type step --coupling 1e-3 --switch-time 10 \\
                                --dipole-fdr-field-direction 1 0 0 \\
                                --dipole-fdr-field-strength 1e-6 --runtime 200
"""
    )
    
    # Parse only known arguments, pass the rest to the simulation script
    parser.add_argument('--replica', type=int, default=0,
                       help='Replica number for both clones (default: 0)')
    parser.add_argument('--dipole-fdr-field-strength', type=float, default=1e-5,
                       help='Electric field strength E₀ (default: 1e-5)')
    parser.add_argument('--dipole-fdr-field-direction', type=float, nargs=3, default=[0, 0, 1],
                       help='Electric field direction [x, y, z] (default: [0, 0, 1])')
    parser.add_argument('--skip-analysis', action='store_true',
                       help='Skip FDR analysis, only run simulations')
    parser.add_argument('--analysis-only', action='store_true', 
                       help='Skip simulations, only perform FDR analysis')
    parser.add_argument('--output-prefix', type=str, default='fdr_analysis',
                       help='Prefix for output files (default: fdr_analysis)')
    
    # Parse known args, pass rest to simulation
    known_args, unknown_args = parser.parse_known_args()
    
    replica = known_args.replica
    field_strength = known_args.dipole_fdr_field_strength
    field_direction = known_args.dipole_fdr_field_direction
    
    logger.info(" Dipole Moment FDR Fork-and-Clone Workflow")
    logger.info(f"   Replica: {replica}")
    logger.info(f"   Field strength: {field_strength:.2e}")
    logger.info(f"   Field direction: {field_direction}")
    logger.info(f"   Base simulation args: {unknown_args}")
    
    success = True
    
    # Phase 1: Run simulations (unless analysis-only)
    if not known_args.analysis_only:
        logger.info("\n Phase 1: Running fork-and-clone simulations")
        
        # Run plus clone
        plus_success = run_simulation(unknown_args, "plus", replica)
        
        # Run minus clone  
        minus_success = run_simulation(unknown_args, "minus", replica)
        
        if not (plus_success and minus_success):
            logger.error(" One or both simulations failed!")
            success = False
        else:
            logger.info(" Both clones completed successfully")
    
    # Phase 2: Analyze results (unless skip-analysis or simulation failed)
    if not known_args.skip_analysis and success:
        logger.info("\n Phase 2: FDR Analysis")
        
        # Find output files
        files = find_output_files(replica)
        
        if files['dipole_fdr']:
            # For now, assume both clones write to the same files
            # In a more sophisticated implementation, we'd need separate file management
            plus_file = files['dipole_fdr'] 
            minus_file = files['dipole_fdr']  # Same file for now
            autocorr_file = files['autocorr_plus'] or files['autocorr_minus']
            
            if plus_file and minus_file and autocorr_file:
                results = analyze_fdr_data(plus_file, minus_file, autocorr_file,
                                         field_strength, field_direction)
                
                if results:
                    output_file = f"{known_args.output_prefix}_replica_{replica}.csv"
                    save_fdr_results(results, output_file)
                else:
                    success = False
            else:
                logger.error(" Required data files not found")
                success = False
        else:
            logger.error(" No dipole FDR data files found")
            success = False
    
    # Summary
    if success:
        logger.info("\n Fork-and-clone FDR workflow completed successfully!")
        logger.info("   Check the output files for detailed results.")
    else:
        logger.error("\n Fork-and-clone FDR workflow failed!")
        sys.exit(1)

if __name__ == "__main__":
    main()
