#!/usr/bin/env python3
"""
Plot Adaptive Temperature Feedback Results

This script plots the instantaneous fictive temperature and applied temperature
over time from the empirical feedback CSV files generated by the adaptive
temperature simulation.
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import argparse
from pathlib import Path
import glob
import sys
import os

# Add the source directory to the path to import EmpiricalTemperatureData
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))
try:
    from cavitymd.analysis import EmpiricalTemperatureData
    EMPIRICAL_DATA_AVAILABLE = True
except ImportError:
    print("Warning: Could not import EmpiricalTemperatureData. Empirical harmonic temperature will not be available.")
    EMPIRICAL_DATA_AVAILABLE = False

def calculate_harmonic_fictive_temperature(harmonic_energy_hartree, n_particles=500):
    """
    Calculate fictive temperature from harmonic bond energy using equipartition theorem.
    
    Parameters
    ----------
    harmonic_energy_hartree : array-like
        Harmonic bond energy in Hartree
    n_particles : int, optional
        Number of particles (default: 500)
        
    Returns
    -------
    T_fictive : array-like
        Fictive temperature in Kelvin
        
    Notes
    -----
    Uses the equipartition theorem for harmonic oscillators:
    T = U * 4 / (N * k_B)
    where the factor of 4 accounts for the additional factor of 2 for harmonic oscillators.
    """
    k_B_hartree = 3.1668105e-6  # Hartree/K (Boltzmann constant)
    
    # Convert to numpy array for calculation
    harmonic_energy = np.asarray(harmonic_energy_hartree)
    
    # T = U * 4 / (N * k_B) for harmonic oscillators (equipartition theorem)
    T_fictive = harmonic_energy * 4.0 / (n_particles * k_B_hartree)
    
    # Only keep physically reasonable temperatures
    reasonable_mask = (T_fictive > 0) & (T_fictive < 10000)
    T_fictive_clean = T_fictive.copy()
    T_fictive_clean[~reasonable_mask] = np.nan
    
    return T_fictive_clean

def calculate_empirical_harmonic_temperature(harmonic_energy_hartree, empirical_data_file, n_particles=500):
    """
    Calculate systemic temperature from harmonic energy using empirical data.
    
    This function loads empirical energy-temperature data and uses the Rosenfeld-Tarazona
    scaling model to determine the systemic temperature that would produce the given
    harmonic energy in equilibrium.
    
    Parameters
    ----------
    harmonic_energy_hartree : array-like
        Harmonic bond energy in Hartree
    empirical_data_file : str or Path
        Path to the empirical energy-temperature data file
    n_particles : int, optional
        Number of particles (default: 500)
        
    Returns
    -------
    T_empirical : array-like
        Empirical systemic temperature in Kelvin
        
    Notes
    -----
    Uses empirical energy-temperature relationship from equilibrium simulations
    with Rosenfeld-Tarazona scaling: E(T) = E₀ + A*T^α
    """
    if not EMPIRICAL_DATA_AVAILABLE:
        print("Warning: EmpiricalTemperatureData not available. Returning NaN.")
        return np.full_like(harmonic_energy_hartree, np.nan)
    
    try:
        # Load empirical data for harmonic energy component
        # Use T^(3/2) correction model for best low-temperature extrapolation
        empirical_data = EmpiricalTemperatureData(
            data_file_path=str(empirical_data_file),
            energy_component='harmonic',
            use_direct_harmonic=False,  # Use fitted function, not direct calculation
            use_linear_harmonic=False,   # Use T^(3/2) correction model instead of linear
            use_t32_harmonic=True        # Enable T^(3/2) correction model
        )
        
        # Convert to numpy array for calculation
        harmonic_energy = np.asarray(harmonic_energy_hartree)
        
        # Calculate systemic temperatures using empirical data
        T_empirical = np.zeros_like(harmonic_energy)
        for i, energy in enumerate(harmonic_energy):
            T_empirical[i] = empirical_data.calculate_systemic_temperature(
                instantaneous_energy_hartree=energy,
                num_particles=n_particles
            )
        
        # Only keep physically reasonable temperatures
        reasonable_mask = (T_empirical > 0) & (T_empirical < 10000)
        T_empirical_clean = T_empirical.copy()
        T_empirical_clean[~reasonable_mask] = np.nan
        
        # Check for extrapolation and warn if temperatures are very low
        T_min_empirical = empirical_data.temperatures.min()
        T_max_empirical = empirical_data.temperatures.max()
        
        extrapolated_mask = T_empirical_clean < T_min_empirical
        n_extrapolated = np.sum(extrapolated_mask & ~np.isnan(T_empirical_clean))
        
        print(f"Calculated empirical harmonic temperatures: {np.nanmin(T_empirical_clean):.1f} - {np.nanmax(T_empirical_clean):.1f} K")
        print(f"Empirical data range: {T_min_empirical:.1f} - {T_max_empirical:.1f} K")
        
        if n_extrapolated > 0:
            min_extrap_T = np.nanmin(T_empirical_clean[extrapolated_mask])
            print(f"  EXTRAPOLATION: {n_extrapolated} points below {T_min_empirical:.1f}K (lowest: {min_extrap_T:.1f}K)")
            print(f"   Extrapolation range: {T_min_empirical - min_extrap_T:.1f}K")
            if T_min_empirical - min_extrap_T > 40:
                print(f"     Large extrapolation! Consider uncertainty analysis.")
        else:
            print(" All temperatures within empirical data range")
        
        return T_empirical_clean
        
    except Exception as e:
        print(f"Warning: Could not calculate empirical harmonic temperature: {e}")
        return np.full_like(harmonic_energy_hartree, np.nan)

def load_energy_tracker_data(energy_file):
    """
    Load energy tracker data to get harmonic energy.
    
    Parameters
    ----------
    energy_file : str or Path
        Path to the energy tracker file
        
    Returns
    -------
    energy_df : pd.DataFrame
        DataFrame with energy data including harmonic_energy column
    """
    try:
        # Read the energy tracker file (skip comment lines)
        energy_df = pd.read_csv(energy_file, sep=r'\s+', comment='#')
        return energy_df
    except Exception as e:
        print(f"Warning: Could not load energy tracker data: {e}")
        return None

def plot_temperature_feedback_overlay(csv_file_1, csv_file_2=None, output_file=None, show_plot=True, 
                                     empirical_data_file_1=None, empirical_data_file_2=None,
                                     replica_number_1=None, replica_number_2=None,
                                     label_1="Dataset 1", label_2="Dataset 2"):
    """
    Plot temperature feedback results with optional overlay of two datasets.
    
    Parameters
    ----------
    csv_file_1 : str
        Path to the first empirical feedback or temperature drop CSV file
    csv_file_2 : str, optional
        Path to the second empirical feedback or temperature drop CSV file for overlay
    output_file : str, optional
        Output file path for saving the plot
    show_plot : bool, optional
        Whether to display the plot (default: True)
    empirical_data_file_1 : str, optional
        Path to empirical energy-temperature data file for first dataset
    empirical_data_file_2 : str, optional
        Path to empirical energy-temperature data file for second dataset
    replica_number_1 : int, optional
        Replica number for first energy tracker file
    replica_number_2 : int, optional
        Replica number for second energy tracker file
    label_1 : str, optional
        Label for first dataset in legend
    label_2 : str, optional
        Label for second dataset in legend
    """
    
    # If only one dataset, use the original function logic
    if csv_file_2 is None:
        return plot_temperature_feedback_single(csv_file_1, output_file, show_plot, 
                                               empirical_data_file_1, replica_number_1, label_1)
    
    # Load both datasets
    dataset_1 = load_dataset(csv_file_1, empirical_data_file_1, replica_number_1, label_1)
    dataset_2 = load_dataset(csv_file_2, empirical_data_file_2, replica_number_2, label_2)
    
    # Create overlay plot
    return create_overlay_plot(dataset_1, dataset_2, output_file, show_plot)

def load_dataset(csv_file, empirical_data_file=None, replica_number=None, label="Dataset"):
    """
    Load a complete dataset including CSV data, energy tracker data, and calculated temperatures.
    
    Returns
    -------
    dict
        Dictionary containing all data and metadata for plotting
    """
    print(f"\n=== Loading {label} ===")
    print(f"Loading feedback data from: {csv_file}")
    
    # Load the feedback data
    df = pd.read_csv(csv_file, comment='#')
    print(f"Feedback data loaded: {len(df)} rows")
    print(f"Time range: {df['time_ps'].min():.3f} to {df['time_ps'].max():.1f} ps")
    
    # Detect file type
    file_type = "unknown"
    if 'instantaneous_T_fictive_K' in df.columns:
        file_type = "empirical_feedback"
        print("Detected: Empirical feedback CSV format")
    elif 'applied_T_K' in df.columns and 'feedback_active' in df.columns:
        file_type = "temperature_drop"
        print("Detected: Temperature drop CSV format")
    else:
        print("Warning: Unknown CSV format. Attempting to detect columns...")
        if any('fictive' in col.lower() for col in df.columns):
            file_type = "auto"
    
    # Auto-detect replica number from CSV filename if not provided
    csv_path = Path(csv_file)
    if replica_number is None:
        import re
        replica_match = re.search(r'replica_(\d+)', csv_path.name)
        if replica_match:
            replica_number = int(replica_match.group(1))
            print(f"Auto-detected replica number: {replica_number}")
        else:
            replica_number = 0  # Default fallback
            print(f"Could not detect replica number from filename, using default: {replica_number}")
    
    # Load energy tracker data
    energy_file = csv_path.parent / f"prod-{replica_number}_energy_tracker.txt"
    energy_df = None
    if energy_file.exists():
        print(f"Loading energy tracker data from: {energy_file}")
        energy_df = load_energy_tracker_data(energy_file)
    else:
        print(f"Warning: Energy tracker file not found: {energy_file}")
    
    # Check if harmonic fictive temperature is already in the CSV (new format)
    T_empirical_harmonic = None
    T_equipartition_harmonic = None
    
    if 'harmonic_T_fictive_K' in df.columns:
        print(" Found harmonic_T_fictive_K column in CSV - using direct values from empirical feedback")
        T_empirical_harmonic = df['harmonic_T_fictive_K'].values
        print(f"Harmonic fictive temperature range: {np.nanmin(T_empirical_harmonic):.1f} - {np.nanmax(T_empirical_harmonic):.1f} K")
        
        # Also use this as equipartition temperature since it's the most accurate
        T_equipartition_harmonic = T_empirical_harmonic.copy()
        
    else:
        print(" harmonic_T_fictive_K column not found - calculating from energy tracker data")
        
        # Calculate empirical harmonic temperature if empirical data file is provided
        if empirical_data_file and EMPIRICAL_DATA_AVAILABLE and energy_df is not None:
            print(f"Calculating empirical harmonic temperature using data from: {empirical_data_file}")
            
            if 'harmonic_energy' in energy_df.columns:
                T_empirical_harmonic = calculate_empirical_harmonic_temperature(
                    harmonic_energy_hartree=energy_df['harmonic_energy'].values,
                    empirical_data_file=empirical_data_file,
                    n_particles=500
                )
                print("Calculated empirical harmonic temperature using T^(3/2) correction systemic approach")
            else:
                print("Warning: Could not find harmonic_energy column in energy tracker data")
        elif empirical_data_file and not EMPIRICAL_DATA_AVAILABLE:
            print("Warning: Empirical data file provided but EmpiricalTemperatureData not available")
        
        # Calculate equipartition harmonic temperature
        if energy_df is not None and 'harmonic_energy' in energy_df.columns:
            kb = 3.16681e-6  # Hartree/K
            n_atoms = 500
            
            if len(energy_df) > 0:
                harmonic_temps = 4 * energy_df['harmonic_energy'].values / (n_atoms * kb)
                energy_time = energy_df['time(ps)'].values
                
                harmonic_temps = pd.to_numeric(harmonic_temps, errors='coerce')
                energy_time = pd.to_numeric(energy_time, errors='coerce')
                
                valid_mask = ~np.isnan(harmonic_temps) & ~np.isnan(energy_time)
                
                if np.sum(valid_mask) > 1:
                    T_equipartition_harmonic = np.interp(df['time_ps'], 
                                                       energy_time[valid_mask], 
                                                       harmonic_temps[valid_mask])
                    print("Calculated harmonic temperature using equipartition theorem")
                else:
                    print("Warning: Not enough valid harmonic energy data points for interpolation")
            else:
                print("Warning: Energy tracker file contains no data rows")
        else:
            print("Warning: Could not find harmonic_energy column in energy tracker data")
    
    # Interpolate empirical harmonic temperature to CSV time points (only if calculated from energy tracker)
    T_empirical_interp = None
    if T_empirical_harmonic is not None:
        if 'harmonic_T_fictive_K' in df.columns:
            # Data is already at CSV time points - no interpolation needed
            T_empirical_interp = T_empirical_harmonic
            print(" Using harmonic fictive temperature directly from CSV (no interpolation needed)")
        elif energy_df is not None:
            # Need to interpolate from energy tracker time points to CSV time points
            energy_time = energy_df['time(ps)'].values
            energy_time = pd.to_numeric(energy_time, errors='coerce')
            valid_mask = ~np.isnan(T_empirical_harmonic) & ~np.isnan(energy_time)
            
            if np.sum(valid_mask) > 1:
                T_empirical_interp = np.interp(df['time_ps'], 
                                             energy_time[valid_mask], 
                                             T_empirical_harmonic[valid_mask])
                print("Interpolated empirical harmonic temperature from energy tracker to CSV time points")
    
    return {
        'df': df,
        'energy_df': energy_df,
        'file_type': file_type,
        'label': label,
        'csv_path': csv_path,
        'T_empirical_interp': T_empirical_interp,
        'T_equipartition_harmonic': T_equipartition_harmonic,
        'empirical_data_file': empirical_data_file,
        'replica_number': replica_number
    }

def create_overlay_plot(dataset_1, dataset_2, output_file=None, show_plot=True):
    """
    Create an overlay plot comparing two datasets.
    """
    # Create the plot
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), sharex=True)
    
    # Define color schemes for the two datasets
    colors_1 = {'fictive_inst': '#1f77b4', 'fictive_avg': '#0d47a1', 'harmonic_csv': '#4caf50', 
               'harmonic_empirical': '#2e7d32', 'harmonic_equip': '#81c784', 'applied': '#f44336', 'energy': '#ff9800'}
    colors_2 = {'fictive_inst': '#ff7f0e', 'fictive_avg': '#d84315', 'harmonic_csv': '#9c27b0', 
               'harmonic_empirical': '#6a1b9a', 'harmonic_equip': '#ba68c8', 'applied': '#e91e63', 'energy': '#795548'}
    
    # Plot first dataset
    plot_dataset_on_axes(ax1, ax2, dataset_1, colors_1, suffix=" (1)")
    
    # Plot second dataset  
    plot_dataset_on_axes(ax1, ax2, dataset_2, colors_2, suffix=" (2)")
    
    # Configure axes
    ax1.set_ylabel('Temperature (K)')
    ax1.set_title('Temperature Feedback Overlay Comparison')
    ax1.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    ax1.grid(True, alpha=0.3)
    
    ax2.set_ylabel('Real Energy (Hartree)')
    ax2.set_xlabel('Time (ps)')
    ax2.set_title('Real Potential Energy (lj_coulombic) Comparison')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # Statistics
    print_overlay_statistics(dataset_1, dataset_2)
    
    plt.tight_layout()
    
    # Save plot if requested
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Overlay plot saved to: {output_file}")
    
    # Show plot
    if show_plot:
        plt.show()
    
    return fig

def plot_dataset_on_axes(ax1, ax2, dataset, colors, suffix=""):
    """
    Plot a single dataset on the provided axes.
    """
    df = dataset['df']
    file_type = dataset['file_type']
    label = dataset['label']
    
    # Plot fictive temperatures
    if file_type in ["empirical_feedback", "temperature_drop"]:
        ax1.plot(df['time_ps'], df['instantaneous_T_fictive_K'], 
                 alpha=0.7, linewidth=0.8, color=colors['fictive_inst'], 
                 label=f'Instantaneous T_fictive ({label}){suffix}')
        
        ax1.plot(df['time_ps'], df['averaged_T_fictive_K'], 
                 linewidth=1.5, color=colors['fictive_avg'], 
                 label=f'Averaged T_fictive ({label}){suffix}')
    else:
        # Try to auto-detect columns
        for col in df.columns:
            if 'instantaneous' in col.lower() and 'fictive' in col.lower():
                ax1.plot(df['time_ps'], df[col], 
                         alpha=0.7, linewidth=0.8, color=colors['fictive_inst'], 
                         label=f'Instantaneous T_fictive ({label}){suffix}')
                break
        
        for col in df.columns:
            if 'averaged' in col.lower() and 'fictive' in col.lower():
                ax1.plot(df['time_ps'], df[col], 
                         linewidth=1.5, color=colors['fictive_avg'], 
                         label=f'Averaged T_fictive ({label}){suffix}')
                break
    
    # Plot harmonic temperatures from CSV
    harmonic_column = None
    if 'harmonic_T_fictive_K' in df.columns:
        harmonic_column = 'harmonic_T_fictive_K'
        label_suffix = 'T_harmonic fictive (CSV)'
    elif 'harmonic_T_K' in df.columns:
        harmonic_column = 'harmonic_T_K'
        label_suffix = 'T_harmonic CSV'
    
    if harmonic_column is not None:
        ax1.plot(df['time_ps'], df[harmonic_column], 
                 linewidth=1.2, color=colors['harmonic_csv'], alpha=0.8,
                 label=f'{label_suffix} ({label}){suffix}')
    
    if dataset['T_empirical_interp'] is not None:
        ax1.plot(df['time_ps'], dataset['T_empirical_interp'], 
                 linewidth=1.2, color=colors['harmonic_empirical'], alpha=0.9,
                 linestyle='--',
                 label=f'T_harmonic empirical ({label}){suffix}')
    
    if dataset['T_equipartition_harmonic'] is not None:
        ax1.plot(df['time_ps'], dataset['T_equipartition_harmonic'], 
                 linewidth=1.2, color=colors['harmonic_equip'], alpha=0.8,
                 linestyle=':',
                 label=f'T_harmonic equipartition ({label}){suffix}')
    
    # Plot applied temperature where it's non-zero
    applied_mask = df['applied_T_K'] > 0
    if applied_mask.any():
        ax1.plot(df.loc[applied_mask, 'time_ps'], 
                df.loc[applied_mask, 'applied_T_K'], 
                linewidth=2, color=colors['applied'], marker='o', markersize=2,
                label=f'Applied T ({label}){suffix}')
    
    # Plot energy
    ax2.plot(df['time_ps'], df['real_energy_hartree'], 
             linewidth=1, color=colors['energy'], alpha=0.8,
             label=f'Energy ({label}){suffix}')

def print_overlay_statistics(dataset_1, dataset_2):
    """
    Print comparison statistics for two datasets.
    """
    print("\n=== Overlay Comparison Statistics ===")
    
    for i, dataset in enumerate([dataset_1, dataset_2], 1):
        df = dataset['df']
        label = dataset['label']
        print(f"\n{label} (Dataset {i}):")
        print(f"  LJ+Coulomb T_fictive (initial): {df['instantaneous_T_fictive_K'].iloc[0]:.2f} K")
        print(f"  LJ+Coulomb T_fictive (final): {df['instantaneous_T_fictive_K'].iloc[-1]:.2f} K")
        print(f"  Energy range (LJ+Coulomb): {df['real_energy_hartree'].min():.6f} - {df['real_energy_hartree'].max():.6f} Hartree")
        
        applied_mask = df['applied_T_K'] > 0
        if applied_mask.any():
            applied_temps = df.loc[applied_mask, 'applied_T_K']
            print(f"  Applied temperature range: {applied_temps.min():.2f} - {applied_temps.max():.2f} K")
        
        if dataset['energy_df'] is not None and 'harmonic_energy' in dataset['energy_df'].columns:
            harmonic_energies = dataset['energy_df']['harmonic_energy']
            print(f"  Energy range (Harmonic): {harmonic_energies.min():.6f} - {harmonic_energies.max():.6f} Hartree")

def plot_temperature_feedback_single(csv_file, output_file=None, show_plot=True, empirical_data_file=None, replica_number=None, label="Dataset"):
    """
    Plot temperature feedback for a single dataset (legacy compatibility function).
    """
    dataset = load_dataset(csv_file, empirical_data_file, replica_number, label)
    return create_single_plot(dataset, output_file, show_plot)

def create_single_plot(dataset, output_file=None, show_plot=True):
    """
    Create a plot for a single dataset.
    """
    colors = {'fictive_inst': '#1f77b4', 'fictive_avg': '#0d47a1', 'harmonic_csv': '#4caf50', 
              'harmonic_empirical': '#2e7d32', 'harmonic_equip': '#81c784', 'applied': '#f44336', 'energy': '#ff9800'}
    
    # Create the plot
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), sharex=True)
    
    # Plot the dataset
    plot_dataset_on_axes(ax1, ax2, dataset, colors)
    
    # Configure axes
    ax1.set_ylabel('Temperature (K)')
    ax1.set_title(f'Temperature Feedback: {dataset["label"]}')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    ax2.set_ylabel('Real Energy (Hartree)')
    ax2.set_xlabel('Time (ps)')
    ax2.set_title('Real Potential Energy (lj_coulombic)')
    ax2.grid(True, alpha=0.3)
    
    # Statistics
    print_single_statistics(dataset)
    
    plt.tight_layout()
    
    # Save plot if requested
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Plot saved to: {output_file}")
    
    # Show plot
    if show_plot:
        plt.show()
    
    return fig

def print_single_statistics(dataset):
    """
    Print statistics for a single dataset.
    """
    df = dataset['df']
    label = dataset['label']
    
    print(f"\n=== Temperature Statistics ({label}) ===")
    print(f"LJ+Coulomb T_fictive (initial): {df['instantaneous_T_fictive_K'].iloc[0]:.2f} K")
    print(f"LJ+Coulomb T_fictive (final): {df['instantaneous_T_fictive_K'].iloc[-1]:.2f} K")
    
    applied_mask = df['applied_T_K'] > 0
    if applied_mask.any():
        applied_temps = df.loc[applied_mask, 'applied_T_K']
        print(f"Applied temperature range: {applied_temps.min():.2f} - {applied_temps.max():.2f} K")
        temp_changes = df.loc[applied_mask, 'applied_T_K'].diff().abs() > 0.001
        num_updates = temp_changes.sum()
        print(f"Number of temperature updates: {num_updates}")
        
        feedback_times = df.loc[df['feedback_active'] == 1, 'time_ps'].values
        if len(feedback_times) > 1:
            intervals = np.diff(feedback_times)
            mean_interval = np.mean(intervals)
            print(f"Average feedback interval: {mean_interval:.2f} ps")
    
    print(f"Energy range (LJ+Coulomb): {df['real_energy_hartree'].min():.6f} - {df['real_energy_hartree'].max():.6f} Hartree")
    
    if dataset['energy_df'] is not None and 'harmonic_energy' in dataset['energy_df'].columns:
        harmonic_energies = dataset['energy_df']['harmonic_energy']
        print(f"Energy range (Harmonic): {harmonic_energies.min():.6f} - {harmonic_energies.max():.6f} Hartree")
    
def find_feedback_files(directory='.'):
    """Find all empirical feedback and temperature drop CSV files in a directory."""
    files = []
    
    # Search for empirical feedback files
    pattern = '**/empirical_feedback_*.csv'
    files.extend(Path(directory).glob(pattern))
    
    # Search for temperature drop files  
    pattern = '**/temperature_drop_*.csv'
    files.extend(Path(directory).glob(pattern))
    
    # Also search for legacy temperature files
    pattern = '**/temperature_*.csv'
    files.extend(Path(directory).glob(pattern))
    
    return sorted(set(files))  # Remove duplicates and sort

def main():
    parser = argparse.ArgumentParser(
        description='Plot adaptive temperature feedback results',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument('csv_file', nargs='?', 
                       help='Path to empirical feedback or temperature drop CSV file (if not provided, will search for files)')
    parser.add_argument('--output', '-o', type=str,
                       help='Output file path for saving the plot')
    parser.add_argument('--no-show', action='store_true',
                       help='Do not display the plot')
    parser.add_argument('--search-dir', type=str, default='.',
                       help='Directory to search for feedback/temperature drop files (default: current)')
    parser.add_argument('--empirical-data', type=str,
                       help='Path to empirical energy-temperature data file for calculating empirical harmonic temperature')
    parser.add_argument('--replica-number', type=int, default=None,
                       help='Replica number for energy tracker file (default: auto-detect from filename)')
    
    # Overlay plotting arguments
    parser.add_argument('--csv-file-2', type=str,
                       help='Path to second empirical feedback or temperature drop CSV file for overlay comparison')
    parser.add_argument('--empirical-data-2', type=str,
                       help='Path to empirical energy-temperature data file for second dataset')
    parser.add_argument('--replica-number-2', type=int, default=None,
                       help='Replica number for second energy tracker file (default: auto-detect from filename)')
    parser.add_argument('--label-1', type=str, default='Dataset 1',
                       help='Label for first dataset in legend (default: Dataset 1)')
    parser.add_argument('--label-2', type=str, default='Dataset 2',
                       help='Label for second dataset in legend (default: Dataset 2)')
    
    args = parser.parse_args()
    
    # Find CSV file
    if args.csv_file:
        csv_file = Path(args.csv_file)
        if not csv_file.exists():
            print(f"Error: File not found: {csv_file}")
            return 1
    else:
        # Search for feedback files
        feedback_files = find_feedback_files(args.search_dir)
        
        if not feedback_files:
            print(f"No empirical feedback CSV files found in {args.search_dir}")
            print("Expected pattern: **/empirical_feedback_*.csv")
            return 1
        
        if len(feedback_files) == 1:
            csv_file = feedback_files[0]
            print(f"Found feedback file: {csv_file}")
        else:
            print(f"Found {len(feedback_files)} feedback files:")
            for i, f in enumerate(feedback_files):
                print(f"  {i+1}: {f}")
            
            try:
                choice = int(input("Select file number: ")) - 1
                csv_file = feedback_files[choice]
            except (ValueError, IndexError):
                print("Invalid selection. Using the first file.")
                csv_file = feedback_files[0]
    
    # Generate output filename if not provided
    if not args.output:
        base_name = csv_file.stem.replace('empirical_feedback_', 'temperature_feedback_')
        args.output = csv_file.parent / f"{base_name}.png"
    
    # Create the plot
    try:
        # Check if overlay mode is requested
        if args.csv_file_2:
            # Overlay mode
            plot_temperature_feedback_overlay(
                csv_file_1=csv_file,
                csv_file_2=args.csv_file_2,
                output_file=args.output,
                show_plot=not args.no_show,
                empirical_data_file_1=args.empirical_data,
                empirical_data_file_2=args.empirical_data_2,
                replica_number_1=args.replica_number,
                replica_number_2=args.replica_number_2,
                label_1=args.label_1,
                label_2=args.label_2
            )
            print(" Temperature feedback overlay plot completed successfully!")
        else:
            # Single plot mode
            plot_temperature_feedback_single(
                csv_file=csv_file,
                output_file=args.output,
                show_plot=not args.no_show,
                empirical_data_file=args.empirical_data,
                replica_number=args.replica_number,
                label=args.label_1
            )
            print(" Temperature feedback plot completed successfully!")
        return 0
        
    except Exception as e:
        print(f" Error creating plot: {e}")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    exit(main())
