#!/usr/bin/env python3
"""
Plot Comprehensive Temperature Tracker Results

This script automatically detects and plots temperature tracker CSV files
generated by the --enable-temp-tracker flag in cavity MD simulations.

The script plots all 6 temperature types:
1. Kinetic temperature (from particle velocities)
2. Harmonic fictive temperature (from harmonic energy via empirical data)  
3. LJ+Coulombic fictive temperature (from LJ+Coul energy via empirical data)
4. Cavity bath temperature (thermostat setting)
5. Molecular bath temperature (thermostat setting)
6. Harmonic equipartition temperature (from harmonic energy via equipartition theorem)
"""

import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import numpy as np
import argparse
from pathlib import Path
import glob
import sys
import os

# Set matplotlib to classic style with LaTeX Computer Modern fonts
plt.style.use('classic')
mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.serif'] = ['Computer Modern Roman']
mpl.rcParams['text.usetex'] = True
mpl.rcParams['text.latex.preamble'] = r'\usepackage{amsmath,amsfonts,amssymb}'
mpl.rcParams['axes.linewidth'] = 1.2
mpl.rcParams['axes.labelsize'] = 12
mpl.rcParams['axes.titlesize'] = 14
mpl.rcParams['xtick.labelsize'] = 11
mpl.rcParams['ytick.labelsize'] = 11
mpl.rcParams['legend.fontsize'] = 11
mpl.rcParams['figure.titlesize'] = 16

def find_temperature_tracker_files(directory='.'):
    """Find all temperature tracker CSV files in a directory."""
    files = []
    
    # Search for temperature tracker files
    pattern = '**/temperature_tracker_*.csv'
    files.extend(Path(directory).glob(pattern))
    
    # Also search for legacy temperature files
    pattern = '**/temp_tracker_*.csv'
    files.extend(Path(directory).glob(pattern))
    
    return sorted(set(files))  # Remove duplicates and sort

def load_temperature_tracker_data(csv_file):
    """
    Load temperature tracker data and validate format.
    
    Returns
    -------
    dict
        Dictionary containing the DataFrame and metadata
    """
    try:
        # Read the CSV file (skip comment lines)
        df = pd.read_csv(csv_file, comment='#')
        
        # Validate required columns
        required_columns = ['time_ps', 'kinetic_temp_K', 'harmonic_fictive_K', 
                          'lj_coul_fictive_K', 'cavity_bath_K', 'molecular_bath_K']
        
        # Optional columns (for backward compatibility)
        optional_columns = ['harmonic_equipartition_K']
        
        missing_columns = [col for col in required_columns if col not in df.columns]
        if missing_columns:
            print(f"Warning: Missing columns in {csv_file}: {missing_columns}")
            return None
        
        # Clean data - remove any rows with all NaN values
        df = df.dropna(subset=['time_ps'])
        
        if len(df) == 0:
            print(f"Warning: No valid data rows found in {csv_file}")
            return None
        
        # Convert to numeric, replacing invalid values with NaN
        for col in required_columns[1:]:  # Skip time_ps
            df[col] = pd.to_numeric(df[col], errors='coerce')
        
        print(f"Loaded temperature tracker data: {len(df)} rows")
        print(f"Time range: {df['time_ps'].min():.3f} to {df['time_ps'].max():.1f} ps")
        
        return {
            'df': df,
            'csv_path': Path(csv_file),
            'n_points': len(df)
        }
        
    except Exception as e:
        print(f"Error loading {csv_file}: {e}")
        return None

def plot_temperature_tracker(csv_file, output_file=None, show_plot=True, label="Dataset"):
    """
    Plot comprehensive temperature tracker results.
    
    Parameters
    ----------
    csv_file : str
        Path to temperature tracker CSV file
    output_file : str, optional
        Output file path for saving the plot
    show_plot : bool, optional
        Whether to display the plot (default: True)
    label : str, optional
        Label for the dataset in legend
    """
    
    print(f"\n=== Plotting Temperature Tracker Data ===")
    print(f"Loading data from: {csv_file}")
    
    # Load the data
    dataset = load_temperature_tracker_data(csv_file)
    if dataset is None:
        return None
    
    df = dataset['df']
    
    # Create the plot
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10), sharex=True)
    
    # Define colors using classic matplotlib colorwheel (Tab10)
    colors = {
        'kinetic': 'C0',          # Classic blue
        'harmonic': 'C1',         # Classic orange  
        'lj_coul': 'C2',          # Classic green
        'cavity_bath': 'C3',      # Classic red
        'molecular_bath': 'C4',   # Classic purple
        'harmonic_equipartition': 'C5'  # Classic brown
    }
    
    # Plot 1: All temperatures
    time = df['time_ps']
    
    # Plot kinetic temperature
    ax1.plot(time, df['kinetic_temp_K'], 
             color=colors['kinetic'], linewidth=1.5, alpha=0.8,
             label=r'Kinetic Temperature')
    
    # Plot harmonic fictive temperature
    harmonic_mask = df['harmonic_fictive_K'] > 0  # Only plot non-zero values
    if harmonic_mask.any():
        ax1.plot(time[harmonic_mask], df.loc[harmonic_mask, 'harmonic_fictive_K'], 
                 color=colors['harmonic'], linewidth=1.5, alpha=0.8,
                 label=r'Harmonic Fictive Temperature')
    
    # Plot LJ+Coul fictive temperature  
    lj_coul_mask = df['lj_coul_fictive_K'] > 0  # Only plot non-zero values
    if lj_coul_mask.any():
        ax1.plot(time[lj_coul_mask], df.loc[lj_coul_mask, 'lj_coul_fictive_K'], 
                 color=colors['lj_coul'], linewidth=1.5, alpha=0.8,
                 label=r'LJ+Coulombic Fictive Temperature')
    
    # Plot harmonic equipartition temperature (if available)
    if 'harmonic_equipartition_K' in df.columns:
        harmonic_eq_mask = df['harmonic_equipartition_K'] > 0  # Only plot non-zero values
        if harmonic_eq_mask.any():
            ax1.plot(time[harmonic_eq_mask], df.loc[harmonic_eq_mask, 'harmonic_equipartition_K'], 
                     color=colors['harmonic_equipartition'], linewidth=1.5, alpha=0.8, linestyle='--',
                     label=r'Harmonic Equipartition Temperature')
    
    # Plot bath temperatures (usually constant)
    ax1.plot(time, df['cavity_bath_K'], 
             color=colors['cavity_bath'], linewidth=2, alpha=0.7,
             linestyle='--', label=r'Cavity Bath Temperature')
    
    ax1.plot(time, df['molecular_bath_K'], 
             color=colors['molecular_bath'], linewidth=2, alpha=0.7,
             linestyle=':', label=r'Molecular Bath Temperature')
    
    # Configure first subplot
    ax1.set_ylabel(r'Temperature (K)')
    ax1.set_title(r'Comprehensive Temperature Tracking: ' + f'{dataset["csv_path"].stem}'.replace('_', r'\_'))
    ax1.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    ax1.grid(True, alpha=0.3)
    
    # Plot 2: Focus on fictive temperatures (excluding bath temperatures)
    ax2.plot(time, df['kinetic_temp_K'], 
             color=colors['kinetic'], linewidth=1.5, alpha=0.8,
             label=r'Kinetic Temperature')
    
    if harmonic_mask.any():
        ax2.plot(time[harmonic_mask], df.loc[harmonic_mask, 'harmonic_fictive_K'], 
                 color=colors['harmonic'], linewidth=1.5, alpha=0.8,
                 label=r'Harmonic Fictive Temperature')
    
    if lj_coul_mask.any():
        ax2.plot(time[lj_coul_mask], df.loc[lj_coul_mask, 'lj_coul_fictive_K'], 
                 color=colors['lj_coul'], linewidth=1.5, alpha=0.8,
                 label=r'LJ+Coulombic Fictive Temperature')
    
    # Plot harmonic equipartition temperature in detail view (if available)
    if 'harmonic_equipartition_K' in df.columns:
        harmonic_eq_mask = df['harmonic_equipartition_K'] > 0  # Only plot non-zero values
        if harmonic_eq_mask.any():
            ax2.plot(time[harmonic_eq_mask], df.loc[harmonic_eq_mask, 'harmonic_equipartition_K'], 
                     color=colors['harmonic_equipartition'], linewidth=1.5, alpha=0.8, linestyle='--',
                     label=r'Harmonic Equipartition Temperature')
    
    # Configure second subplot
    ax2.set_ylabel(r'Temperature (K)')
    ax2.set_xlabel(r'Time (ps)')
    ax2.set_title(r'Fictive and Kinetic Temperatures (Detail View)')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # Add vertical line if there's a clear jump indicating coupling turn-on
    kinetic_temps = df['kinetic_temp_K'].values
    if len(kinetic_temps) > 10:
        # Look for large jumps in kinetic temperature
        diff = np.abs(np.diff(kinetic_temps))
        max_jump_idx = np.argmax(diff)
        if diff[max_jump_idx] > 50:  # Threshold for significant temperature jump
            switch_time = df['time_ps'].iloc[max_jump_idx]
            for ax in [ax1, ax2]:
                ax.axvline(switch_time, color='red', linestyle='--', alpha=0.5, 
                          label=f'Coupling Switch ({switch_time:.1f} ps)')
            print(f"Detected coupling switch at t = {switch_time:.1f} ps")
    
    plt.tight_layout()
    
    # Print statistics
    print_statistics(dataset)
    
    # Save plot if requested
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Temperature tracker plot saved to: {output_file}")
    
    # Show plot
    if show_plot:
        plt.show()
    
    return fig

def print_statistics(dataset):
    """Print statistics for the temperature tracker data."""
    df = dataset['df']
    
    print(f"\n=== Temperature Statistics ===")
    print(f"Data points: {len(df)}")
    print(f"Time range: {df['time_ps'].min():.3f} - {df['time_ps'].max():.1f} ps")
    print(f"")
    
    # Statistics for each temperature type
    for temp_type in ['kinetic_temp_K', 'harmonic_fictive_K', 'lj_coul_fictive_K']:
        temps = df[temp_type]
        valid_temps = temps[temps > 0]  # Exclude zeros
        
        if len(valid_temps) > 0:
            temp_name = temp_type.replace('_temp_K', '').replace('_fictive_K', ' fictive').replace('_', ' ').title()
            print(f"{temp_name}:")
            print(f"  Range: {valid_temps.min():.1f} - {valid_temps.max():.1f} K")
            print(f"  Mean: {valid_temps.mean():.1f} ± {valid_temps.std():.1f} K")
            print(f"  Valid points: {len(valid_temps)}/{len(temps)}")
        else:
            temp_name = temp_type.replace('_temp_K', '').replace('_fictive_K', ' fictive').replace('_', ' ').title()
            print(f"{temp_name}: No valid data (all zeros)")
        print("")
    
    # Bath temperature consistency
    cavity_bath = df['cavity_bath_K']
    molecular_bath = df['molecular_bath_K']
    print(f"Bath Temperatures:")
    print(f"  Cavity bath: {cavity_bath.mean():.1f} K (std: {cavity_bath.std():.3f})")
    print(f"  Molecular bath: {molecular_bath.mean():.1f} K (std: {molecular_bath.std():.3f})")

def plot_multiple_temperature_trackers(csv_files, output_file=None, show_plot=True):
    """
    Plot multiple temperature tracker datasets for comparison.
    
    Parameters
    ----------
    csv_files : list
        List of paths to temperature tracker CSV files
    output_file : str, optional
        Output file path for saving the plot
    show_plot : bool, optional
        Whether to display the plot (default: True)
    """
    
    if len(csv_files) < 2:
        print("Need at least 2 files for comparison plot")
        return None
    
    print(f"\n=== Plotting Multiple Temperature Tracker Datasets ===")
    
    # Load all datasets
    datasets = []
    for csv_file in csv_files:
        dataset = load_temperature_tracker_data(csv_file)
        if dataset is not None:
            dataset['label'] = Path(csv_file).stem
            datasets.append(dataset)
    
    if len(datasets) == 0:
        print("No valid datasets loaded")
        return None
    
    # Create the plot
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(16, 12))
    
    # Define color cycle using classic matplotlib colors
    classic_colors = ['C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9']
    color_cycle = [classic_colors[i % len(classic_colors)] for i in range(len(datasets))]
    
    for i, dataset in enumerate(datasets):
        df = dataset['df']
        time = df['time_ps']
        color = color_cycle[i]
        label = dataset['label']
        
        # Plot kinetic temperatures
        ax1.plot(time, df['kinetic_temp_K'], 
                color=color, linewidth=1.5, alpha=0.8, label=label)
        
        # Plot harmonic fictive temperatures (empirical)
        harmonic_mask = df['harmonic_fictive_K'] > 0
        if harmonic_mask.any():
            ax2.plot(time[harmonic_mask], df.loc[harmonic_mask, 'harmonic_fictive_K'], 
                    color=color, linewidth=1.5, alpha=0.8, label=f'{label} (Empirical)')
        
        # Plot harmonic equipartition temperatures (if available)
        if 'harmonic_equipartition_K' in df.columns:
            harmonic_eq_mask = df['harmonic_equipartition_K'] > 0
            if harmonic_eq_mask.any():
                ax2.plot(time[harmonic_eq_mask], df.loc[harmonic_eq_mask, 'harmonic_equipartition_K'], 
                        color=color, linewidth=1.5, alpha=0.8, linestyle='--', 
                        label=f'{label} (Equipartition)')
        
        # Plot LJ+Coul fictive temperatures
        lj_coul_mask = df['lj_coul_fictive_K'] > 0
        if lj_coul_mask.any():
            ax3.plot(time[lj_coul_mask], df.loc[lj_coul_mask, 'lj_coul_fictive_K'], 
                    color=color, linewidth=1.5, alpha=0.8, label=label)
        
        # Plot molecular bath temperatures
        ax4.plot(time, df['molecular_bath_K'], 
                color=color, linewidth=2, alpha=0.8, label=label)
    
    # Configure subplots
    ax1.set_title(r'Kinetic Temperature Comparison')
    ax1.set_ylabel(r'Temperature (K)')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    ax2.set_title(r'Harmonic Temperature Comparison (Empirical vs Equipartition)')
    ax2.set_ylabel(r'Temperature (K)')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    ax3.set_title(r'LJ+Coulombic Fictive Temperature Comparison')
    ax3.set_xlabel(r'Time (ps)')
    ax3.set_ylabel(r'Temperature (K)')
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    ax4.set_title(r'Molecular Bath Temperature Comparison')
    ax4.set_xlabel(r'Time (ps)')
    ax4.set_ylabel(r'Temperature (K)')
    ax4.legend()
    ax4.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    # Save plot if requested
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Comparison plot saved to: {output_file}")
    
    # Show plot
    if show_plot:
        plt.show()
    
    return fig

def main():
    parser = argparse.ArgumentParser(
        description='Plot comprehensive temperature tracker results',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Plot a specific temperature tracker file
  python plot_temperature_tracker.py temperature_tracker_replica_0.csv
  
  # Auto-search for files in current directory
  python plot_temperature_tracker.py
  
  # Compare multiple files
  python plot_temperature_tracker.py file1.csv file2.csv --compare
  
  # Save plot without displaying
  python plot_temperature_tracker.py data.csv --output plot.png --no-show
        """
    )
    
    parser.add_argument('csv_files', nargs='*', 
                       help='Path(s) to temperature tracker CSV file(s) (if not provided, will search for files)')
    parser.add_argument('--output', '-o', type=str,
                       help='Output file path for saving the plot')
    parser.add_argument('--no-show', action='store_true',
                       help='Do not display the plot')
    parser.add_argument('--search-dir', type=str, default='.',
                       help='Directory to search for temperature tracker files (default: current)')
    parser.add_argument('--compare', action='store_true',
                       help='Create comparison plot for multiple files')
    
    args = parser.parse_args()
    
    # Find CSV files
    if args.csv_files:
        csv_files = [Path(f) for f in args.csv_files]
        # Validate files exist
        for f in csv_files:
            if not f.exists():
                print(f"Error: File not found: {f}")
                return 1
    else:
        # Search for temperature tracker files
        csv_files = find_temperature_tracker_files(args.search_dir)
        
        if not csv_files:
            print(f"No temperature tracker CSV files found in {args.search_dir}")
            print("Expected pattern: **/temperature_tracker_*.csv")
            return 1
        
        if len(csv_files) == 1:
            print(f"Found temperature tracker file: {csv_files[0]}")
        else:
            print(f"Found {len(csv_files)} temperature tracker files:")
            for i, f in enumerate(csv_files):
                print(f"  {i+1}: {f}")
            
            if not args.compare:
                try:
                    choice = int(input("Select file number (or 0 for comparison plot): ")) - 1
                    if choice == -1:
                        args.compare = True
                    else:
                        csv_files = [csv_files[choice]]
                except (ValueError, IndexError):
                    print("Invalid selection. Using comparison plot.")
                    args.compare = True
    
    # Generate output filename if not provided
    if not args.output:
        if len(csv_files) == 1:
            base_name = csv_files[0].stem
            args.output = csv_files[0].parent / f"{base_name}_plot.png"
        else:
            args.output = Path(args.search_dir) / "temperature_tracker_comparison.png"
    
    # Create the plot
    try:
        if args.compare or len(csv_files) > 1:
            # Comparison mode
            plot_multiple_temperature_trackers(
                csv_files=csv_files,
                output_file=args.output,
                show_plot=not args.no_show
            )
            print("✅ Temperature tracker comparison plot completed successfully!")
        else:
            # Single plot mode
            plot_temperature_tracker(
                csv_file=csv_files[0],
                output_file=args.output,
                show_plot=not args.no_show
            )
            print("✅ Temperature tracker plot completed successfully!")
        return 0
        
    except Exception as e:
        print(f"❌ Error creating plot: {e}")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    exit(main())
