"""Tests for figure4 CSV export master F(k,t) loading."""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "reproduction" / "csv_export"))

from export_figure4_csv import load_fskt  # noqa: E402


def _write_master(path: Path, *, extra_comment: bool) -> None:
    lines = [
        "# Master F(k,t) file for cavity_coupling_0epos00_switch_200.0ps - ref_000",
        "# Cumulative average across 60 replicas",
        "# Time grid: 0 to 2500.000 ps with 2501 points (dt = 1.0 ps)",
        "# Valid data points: 3 (coverage)",
        "# Sample count range: 60 to 60",
        "# Reference laboratory time: 1.000 ps",
    ]
    if extra_comment:
        lines.append("# Lag grid capped by runtime/reference coverage")
    lines.extend(
        [
            "# Generated by process_fskt_only.py",
            "# Columns: lag_time fskt",
            "lag_time\tfskt",
            "0.0\t1.0",
            "1.0\t0.9",
            "2.0\t0.8",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_load_fskt_skips_variable_comment_header(tmp_path: Path) -> None:
    """RF masters add an extra comment line vs legacy skiprows=9 layout."""
    coupling = tmp_path / "cavity_coupling_0epos00_switch_200.0ps"
    coupling.mkdir()
    _write_master(coupling / "master_fskt_ref_000.txt", extra_comment=True)

    lag, fskt = load_fskt(tmp_path, 0.0, 0, coupling_names={0.0: "0epos00"})
    assert lag is not None
    assert fskt is not None
    np.testing.assert_allclose(lag, [0.0, 1.0, 2.0])
    np.testing.assert_allclose(fskt, [1.0, 0.9, 0.8])


def test_load_fskt_legacy_comment_count(tmp_path: Path) -> None:
    coupling = tmp_path / "cavity_coupling_0epos00_switch_200.0ps"
    coupling.mkdir()
    _write_master(coupling / "master_fskt_ref_000.txt", extra_comment=False)

    lag, fskt = load_fskt(tmp_path, 0.0, 0, coupling_names={0.0: "0epos00"})
    assert lag is not None
    np.testing.assert_allclose(lag[:2], [0.0, 1.0])
