name: cav-hoomd-docs
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python environment
  - python=3.11
  - pip
  
  # HOOMD-blue - the key dependency that was missing!
  - hoomd
  
  # Documentation build tools
  - sphinx>=6.0
  - sphinx-autodoc-typehints>=1.24.0
  - myst-parser>=2.0.0
  - sphinx-copybutton>=0.5.2
  - sphinxcontrib-bibtex>=2.5.0
  - nbsphinx>=0.9.0
  - jupyter
  - ipykernel
  - sphinx-design>=0.5.0
  - sphinx-tabs>=3.4.0
  - furo>=2023.9.10
  - sphinx-autobuild>=2021.3.14
  
  # Scientific computing dependencies
  - numpy
  - matplotlib
  - scipy
  
  # Additional dependencies via pip if needed
  - pip:
    - []  # Add any pip-only packages here if needed 